import Link from "next/link";
export const metadata={title:"Oferta Formativa",description:"Oferta formativa do ensino primário e secundário."};
const faqs=[["Que classes são abrangidas?","A oferta apresentada cobre o ensino primário da 1ª à 6ª classe e o secundário da 7ª à 12ª classe."],["Como funciona a matrícula?","O pedido é submetido online e fica pendente até validação administrativa."],["Como o estudante acede ao portal?","Após aprovação, a secretaria pode emitir o código de acesso individual."],["Os professores podem alterar notas publicadas livremente?","Não. As alterações são controladas, limitadas à atribuição do professor e auditadas."],["Como são protegidos os dados dos estudantes?","O portal aplica controlo por função, RLS, MFA para contas privilegiadas e auditoria de operações sensíveis."]];
export default function Page(){return <main className="container-site py-14">
  <nav aria-label="Breadcrumb" className="mb-5 text-sm"><Link href="/">Início</Link> <span aria-hidden="true">/</span> <span>Oferta Formativa</span></nav>
  <h1 className="text-4xl font-black">Oferta Formativa</h1>
  <div className="mt-8 grid gap-5 md:grid-cols-2"><section className="card p-7"><h2 className="text-2xl font-black">Primário</h2><p className="mt-2">1ª–6ª Classe</p><p className="mt-4 text-slate-600">Língua Portuguesa, Matemática, Ciências Naturais, História, Geografia, Educação Física, Educação Visual e Ofícios.</p></section><section className="card p-7"><h2 className="text-2xl font-black">Secundário</h2><p className="mt-2">7ª–12ª Classe</p><p className="mt-4 text-slate-600">Percurso secundário com disciplinas definidas na matriz curricular institucional e validadas pela direção.</p></section></div>
  <section className="mt-12" aria-labelledby="faq"><h2 id="faq" className="text-3xl font-black">Perguntas frequentes</h2><div className="mt-5 space-y-3">{faqs.map(([q,a])=><details className="card p-5" key={q}><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 text-slate-600">{a}</p></details>)}</div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))})}}/>
</main>}