import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Search, KeyRound, UserCheck, RefreshCw, Copy, X } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { requireSupabase } from "@/lib/supabase";

type Student={id:string;full_name:string;registration_number:string;email:string|null;contact:string|null;status:string;class_id:string;classes?:{level:number;name:string;academic_year:number}|null};
type Request={id:string;full_name:string;contact:string;guardian_name:string;guardian_contact:string;class_level:number;class_name:string;status:string;created_at:string};

export const Route=createFileRoute("/admin/alunos")({head:()=>({meta:[{title:"Alunos — Painel Administrativo"},{name:"robots",content:"noindex,nofollow"}]}),component:Students});

function Students(){
 const db=requireSupabase(); const [students,setStudents]=useState<Student[]>([]); const [requests,setRequests]=useState<Request[]>([]);
 const [classes,setClasses]=useState<{id:string;level:number;name:string;academic_year:number}[]>([]);
 const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [tab,setTab]=useState<"students"|"requests">("students");
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [selected,setSelected]=useState<Student|null>(null); const [code,setCode]=useState("");
 async function load(){setBusy(true);const [s,c,r]=await Promise.all([
  db.from("students").select("id,full_name,registration_number,email,contact,status,class_id,classes(level,name,academic_year)").order("full_name"),
  db.from("classes").select("id,level,name,academic_year").order("level").order("name"),
  db.from("registration_requests").select("id,full_name,contact,guardian_name,guardian_contact,class_level,class_name,status,created_at").eq("status","pending").order("created_at",{ascending:false})
 ]);if(s.error||c.error||r.error)setMessage("Não foi possível carregar os dados. Verifique a sessão administrativa e as políticas RLS.");setStudents((s.data as unknown as Student[])||[]);setClasses(c.data||[]);setRequests(r.data||[]);setBusy(false)}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>students.filter(s=>{const q=query.toLowerCase().trim();return(!q||s.full_name.toLowerCase().includes(q)||s.registration_number.toLowerCase().includes(q)||(s.email||"").toLowerCase().includes(q))&&(status==="all"||s.status===status)}),[students,query,status]);
 async function issueCode(s:Student){setBusy(true);setMessage("");const uid=(await db.auth.getUser()).data.user?.id;const {data,error}=await db.rpc("issue_student_auth_code",{p_student_id:s.id,p_actor:uid});if(error){setMessage("Não foi possível gerar o código de acesso.");setBusy(false);return}setSelected(s);setCode(data);setBusy(false);await load()}
 async function approve(r:Request){const target=classes.find(c=>c.level===r.class_level&&c.name.toLowerCase()===r.class_name.toLowerCase())||classes.find(c=>c.level===r.class_level);if(!target){setMessage("Não existe uma turma compatível para esta inscrição.");return}const registration=prompt("Número de matrícula a atribuir ao aluno:");if(!registration?.trim())return;const email=prompt("E-mail do aluno (opcional):")||"";setBusy(true);const uid=(await db.auth.getUser()).data.user?.id;const {error}=await db.rpc("approve_registration",{p_request_id:r.id,p_class_id:target.id,p_registration_number:registration.trim(),p_email:email.trim(),p_actor:uid});if(error)setMessage(error.message.includes("registration_number_exists")?"Esse número de matrícula já existe.":"Não foi possível aprovar a inscrição.");else{setMessage("Inscrição aprovada. Emita agora o código de acesso.");await load()}setBusy(false)}
 return <AdminShell><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-yellow-600">Gestão académica</p><h2 className="mt-1 text-3xl font-bold text-primary">Alunos</h2><p className="mt-2 text-muted-foreground">Pesquisa, aprovação de inscrições e emissão de códigos de acesso.</p></div><button onClick={load} disabled={busy} className="inline-flex items-center gap-2 rounded-lg border bg-background px-4 py-2.5 text-sm font-semibold"><RefreshCw className={busy?"h-4 w-4 animate-spin":"h-4 w-4"}/>Atualizar</button></div>
 {message&&<div className="mt-5 rounded-lg border bg-yellow-50 p-3 text-sm text-yellow-900">{message}</div>}
 {selected&&code&&<div className="mt-5 rounded-xl border-2 border-yellow-400 bg-yellow-50 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-yellow-700">Código gerado — mostrar apenas uma vez</p><h3 className="mt-1 font-bold text-primary">{selected.full_name}</h3><p className="text-sm text-muted-foreground">Matrícula: {selected.registration_number}</p></div><button onClick={()=>{setSelected(null);setCode("")}}><X className="h-5 w-5"/></button></div><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center"><code className="rounded-lg bg-background px-5 py-3 text-2xl font-bold tracking-[0.25em]">{code}</code><button onClick={()=>navigator.clipboard.writeText(code)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground"><Copy className="h-4 w-4"/>Copiar código</button></div></div>}
 <div className="mt-7 flex gap-2 border-b"><button onClick={()=>setTab("students")} className={"border-b-2 px-4 py-3 text-sm font-semibold "+(tab==="students"?"border-yellow-400 text-primary":"border-transparent text-muted-foreground")}>Alunos ({students.length})</button><button onClick={()=>setTab("requests")} className={"border-b-2 px-4 py-3 text-sm font-semibold "+(tab==="requests"?"border-yellow-400 text-primary":"border-transparent text-muted-foreground")}>Inscrições pendentes ({requests.length})</button></div>
 {tab==="students"&&<><div className="mt-5 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar por nome, matrícula ou e-mail" className="w-full rounded-lg border bg-background py-2.5 pl-10 pr-3"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border bg-background px-3 py-2.5"><option value="all">Todos os estados</option><option value="active">Ativos</option><option value="pending">Pendentes</option><option value="blocked">Bloqueados</option><option value="inactive">Inativos</option></select></div><div className="mt-5 overflow-x-auto rounded-xl border bg-background"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-4 py-3">Aluno</th><th className="px-4 py-3">Matrícula</th><th className="px-4 py-3">Turma</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3 text-right">Ações</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id} className="border-b last:border-0"><td className="px-4 py-3 font-semibold">{s.full_name}<div className="text-xs font-normal text-muted-foreground">{s.email||s.contact||"Sem contacto"}</div></td><td className="px-4 py-3 font-mono">{s.registration_number}</td><td className="px-4 py-3">{s.classes?s.classes.level+"ª — "+s.classes.name+" ("+s.classes.academic_year+")":"—"}</td><td className="px-4 py-3"><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{s.status}</span></td><td className="px-4 py-3 text-right"><button onClick={()=>issueCode(s)} disabled={busy} className="inline-flex items-center gap-2 rounded-md bg-yellow-400 px-3 py-2 text-xs font-bold text-black"><KeyRound className="h-3.5 w-3.5"/>Novo código</button></td></tr>)}</tbody></table>{filtered.length===0&&<p className="p-8 text-center text-sm text-muted-foreground">Nenhum aluno encontrado.</p>}</div></>}
 {tab==="requests"&&<div className="mt-5 space-y-3">{requests.length===0&&<div className="rounded-xl border bg-background p-8 text-center text-sm text-muted-foreground">Não existem inscrições pendentes.</div>}{requests.map(r=><div key={r.id} className="rounded-xl border bg-background p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-bold text-primary">{r.full_name}</p><p className="mt-1 text-sm text-muted-foreground">{r.class_level}ª classe · {r.class_name} · {r.contact}</p><p className="mt-1 text-xs text-muted-foreground">Encarregado: {r.guardian_name} · {r.guardian_contact}</p></div><button onClick={()=>approve(r)} disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-lg bg-yellow-400 px-4 py-2.5 text-sm font-bold text-black"><UserCheck className="h-4 w-4"/>Aprovar inscrição</button></div></div>)}</div>}</AdminShell>;
}
