/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmissoesRouteImport } from './routes/admissoes'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as EnsinoRouteImport } from './routes/ensino'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminDefinicoesRouteImport } from './routes/admin.definicoes'
import { Route as AdminDisciplinasRouteImport } from './routes/admin.disciplinas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMateriaisRouteImport } from './routes/admin.materiais'
import { Route as AdminNotasRouteImport } from './routes/admin.notas'
import { Route as AdminNoticiasRouteImport } from './routes/admin.noticias'
import { Route as AdminPresencasRouteImport } from './routes/admin.presencas'
import { Route as AdminProfessoresRouteImport } from './routes/admin.professores'
import { Route as AdminRedefinirRouteImport } from './routes/admin.redefinir'
import { Route as AdminTurmasRouteImport } from './routes/admin.turmas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissoesRoute = AdmissoesRouteImport.update({
  id: '/admissoes',
  path: '/admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsinoRoute = EnsinoRouteImport.update({
  id: '/ensino',
  path: '/ensino',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDefinicoesRoute = AdminDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisciplinasRoute = AdminDisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriaisRoute = AdminMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotasRoute = AdminNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresencasRoute = AdminPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessoresRoute = AdminProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedefinirRoute = AdminRedefinirRouteImport.update({
  id: '/redefinir',
  path: '/redefinir',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTurmasRoute = AdminTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissoes': typeof AdmissoesRoute
  '/contactos': typeof ContactosRoute
  '/ensino': typeof EnsinoRoute
  '/noticias': typeof NoticiasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/disciplinas': typeof AdminDisciplinasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/notas': typeof AdminNotasRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/redefinir': typeof AdminRedefinirRoute
  '/admin/turmas': typeof AdminTurmasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissoes': typeof AdmissoesRoute
  '/contactos': typeof ContactosRoute
  '/ensino': typeof EnsinoRoute
  '/noticias': typeof NoticiasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/disciplinas': typeof AdminDisciplinasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/notas': typeof AdminNotasRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/redefinir': typeof AdminRedefinirRoute
  '/admin/turmas': typeof AdminTurmasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissoes': typeof AdmissoesRoute
  '/contactos': typeof ContactosRoute
  '/ensino': typeof EnsinoRoute
  '/noticias': typeof NoticiasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/disciplinas': typeof AdminDisciplinasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/notas': typeof AdminNotasRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/redefinir': typeof AdminRedefinirRoute
  '/admin/turmas': typeof AdminTurmasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admissoes'
    | '/contactos'
    | '/ensino'
    | '/noticias'
    | '/privacidade'
    | '/sobre'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/definicoes'
    | '/admin/disciplinas'
    | '/admin/login'
    | '/admin/materiais'
    | '/admin/notas'
    | '/admin/noticias'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/redefinir'
    | '/admin/turmas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admissoes'
    | '/contactos'
    | '/ensino'
    | '/noticias'
    | '/privacidade'
    | '/sobre'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/definicoes'
    | '/admin/disciplinas'
    | '/admin/login'
    | '/admin/materiais'
    | '/admin/notas'
    | '/admin/noticias'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/redefinir'
    | '/admin/turmas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admissoes'
    | '/contactos'
    | '/ensino'
    | '/noticias'
    | '/privacidade'
    | '/sobre'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/definicoes'
    | '/admin/disciplinas'
    | '/admin/login'
    | '/admin/materiais'
    | '/admin/notas'
    | '/admin/noticias'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/redefinir'
    | '/admin/turmas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissoesRoute: typeof AdmissoesRoute
  ContactosRoute: typeof ContactosRoute
  EnsinoRoute: typeof EnsinoRoute
  NoticiasRoute: typeof NoticiasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissoes': {
      id: '/admissoes'
      path: '/admissoes'
      fullPath: '/admissoes'
      preLoaderRoute: typeof AdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensino': {
      id: '/ensino'
      path: '/ensino'
      fullPath: '/ensino'
      preLoaderRoute: typeof EnsinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/definicoes': {
      id: '/admin/definicoes'
      path: '/definicoes'
      fullPath: '/admin/definicoes'
      preLoaderRoute: typeof AdminDefinicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disciplinas': {
      id: '/admin/disciplinas'
      path: '/disciplinas'
      fullPath: '/admin/disciplinas'
      preLoaderRoute: typeof AdminDisciplinasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materiais': {
      id: '/admin/materiais'
      path: '/materiais'
      fullPath: '/admin/materiais'
      preLoaderRoute: typeof AdminMateriaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notas': {
      id: '/admin/notas'
      path: '/notas'
      fullPath: '/admin/notas'
      preLoaderRoute: typeof AdminNotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presencas': {
      id: '/admin/presencas'
      path: '/presencas'
      fullPath: '/admin/presencas'
      preLoaderRoute: typeof AdminPresencasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professores': {
      id: '/admin/professores'
      path: '/professores'
      fullPath: '/admin/professores'
      preLoaderRoute: typeof AdminProfessoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redefinir': {
      id: '/admin/redefinir'
      path: '/redefinir'
      fullPath: '/admin/redefinir'
      preLoaderRoute: typeof AdminRedefinirRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/turmas': {
      id: '/admin/turmas'
      path: '/turmas'
      fullPath: '/admin/turmas'
      preLoaderRoute: typeof AdminTurmasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminDefinicoesRoute: typeof AdminDefinicoesRoute
  AdminDisciplinasRoute: typeof AdminDisciplinasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMateriaisRoute: typeof AdminMateriaisRoute
  AdminNotasRoute: typeof AdminNotasRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminPresencasRoute: typeof AdminPresencasRoute
  AdminProfessoresRoute: typeof AdminProfessoresRoute
  AdminRedefinirRoute: typeof AdminRedefinirRoute
  AdminTurmasRoute: typeof AdminTurmasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminDefinicoesRoute: AdminDefinicoesRoute,
  AdminDisciplinasRoute: AdminDisciplinasRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMateriaisRoute: AdminMateriaisRoute,
  AdminNotasRoute: AdminNotasRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminPresencasRoute: AdminPresencasRoute,
  AdminProfessoresRoute: AdminProfessoresRoute,
  AdminRedefinirRoute: AdminRedefinirRoute,
  AdminTurmasRoute: AdminTurmasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissoesRoute: AdmissoesRoute,
  ContactosRoute: ContactosRoute,
  EnsinoRoute: EnsinoRoute,
  NoticiasRoute: NoticiasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
