/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissoesRouteImport } from './routes/admissoes'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as EnsinoRouteImport } from './routes/ensino'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissoesRoute = AdmissoesRouteImport.update({
  id: '/admissoes',
  path: '/admissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsinoRoute = EnsinoRouteImport.update({
  id: '/ensino',
  path: '/ensino',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contactos': typeof ContactosRoute
  '/ensino': typeof EnsinoRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contactos': typeof ContactosRoute
  '/ensino': typeof EnsinoRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissoes': typeof AdmissoesRoute
  '/contactos': typeof ContactosRoute
  '/ensino': typeof EnsinoRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admissoes' | '/contactos' | '/ensino' | '/noticias' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admissoes' | '/contactos' | '/ensino' | '/noticias' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/admissoes'
    | '/contactos'
    | '/ensino'
    | '/noticias'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissoesRoute: typeof AdmissoesRoute
  ContactosRoute: typeof ContactosRoute
  EnsinoRoute: typeof EnsinoRoute
  NoticiasRoute: typeof NoticiasRoute
  SobreRoute: typeof SobreRoute,
  PrivacidadeRoute: typeof PrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissoes': {
      id: '/admissoes'
      path: '/admissoes'
      fullPath: '/admissoes'
      preLoaderRoute: typeof AdmissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensino': {
      id: '/ensino'
      path: '/ensino'
      fullPath: '/ensino'
      preLoaderRoute: typeof EnsinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissoesRoute: AdmissoesRoute,
  ContactosRoute: ContactosRoute,
  EnsinoRoute: EnsinoRoute,
  NoticiasRoute: NoticiasRoute,
  SobreRoute: SobreRoute,
  PrivacidadeRoute: PrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
